environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      TOXENV: py36
    - PYTHON: "C:\\Python37-x64"
      TOXENV: py37

install:
  - "%PYTHON%\\python.exe -m pip install wheel tox pykakasi"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

matrix:
  fast_finish: true