environment:
  TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
  TWINE_USERNAME: miurahr
  TWINE_PASSWORD:
    secure: ibyxU09f3mAdoh5Hv4T27Q==

install:
  - "python.exe -m pip install twine wheel"
  - "python.exe -m pip install -r requirements.txt"

build_script: 
  - "python.exe setup.py build"

test_script:
  - "python.exe setup.py test"

after_test:
  - "python.exe setup.py sdist"

artifacts:
  - path: dist/*.tar.gz

deploy_script:
  - ps: |
      function exec
      {
        param ( [ScriptBlock] $ScriptBlock )
        & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
        if ($LastExitCode -ne 0) { exit $LastExitCode }
      }
      If ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        $artifacts = Get-ChildItem -Path dist -Include '*.tar.gz' -Recurse -Name | %{"$_"}
        cd dist
        exec { python.exe -m twine upload --skip-existing $artifacts }
      }
      else
      {
        Write-Host "Skip uploading artifacts to PyPi when non tag commit"
      }
